### ISSUE TITLE
QuickStart guide, authentication against userdb

### ISSUE THREAD

**Issue by ptomulik** [openxpki/openxpki#228]
The quickstart guide gives this example

```
Password:
    type: Password
    label: User Password
    description: I18N_OPENXPKI_CONFIG_AUTH_HANDLER_DESCRIPTION_PASSWORD
    user@: auth.connector.userdb
```

but it doesn't work (just displays "Authentication failure" or "Unknown error" in UI). After few hours of trials and errors I've discovered that this works:

```
Password:
    type: Password
    label: User Password
    description: I18N_OPENXPKI_CONFIG_AUTH_HANDLER_DESCRIPTION_PASSWORD
    user@: connector:auth.connector.userdb
```

Also, it would be good to provide an example of userdb file, e.g.

```
ca:
    digest: "{ssha}lPtC+l1L+BxfVwiR0t4zFEGWNbNFMmd"
    role: CA Operator
ra:
    digest: "{ssha}lPtC+l1L+BxfVwiR0t4zFEGWNbNFMmd"
    role: RA Operator
```

to show at which level the userdb should start (i.e. to show that it should not contain initial "user:" key).
