### ISSUE TITLE
Add workflow prefix on nested conditons

### ISSUE THREAD

**Issue by oliwel** [openxpki/openxpki#311]
Auto-Add the workflow prefix for nested conditions, e.g.

```
        class: Workflow::Condition::LazyAND
        param:
            condition1: csr_is_operator
            condition2: !csr_is_creator
```
