### ISSUE TITLE
authority_info_access not being added to crl

### ISSUE THREAD

**Issue by DimeOne** [openxpki/openxpki#540]
Hi,

I am using OpenXPKI in version 1.17.4 from the debian package.

I've configured my realm to create crls as in the example. I've set the authority_info_access in the crl/default.yaml as in the example. I've republished by crl but it does not contain authority_info_access.

I've checked using openssl crl -text -noout -in mycrl.crl

Under CRL extension I am only able to find:
   - X509v3 Authority Key Identifier:
   - X509v3 CRL Number:

My crl/default.yaml:

```yaml
validity: 
    # validity interval used while the ca is active (relative date!)
    nextupdate: +000014
    
    # how long before next update a new crl should be issued
    renewal: +000003

    # validity of last crl issued before ca is end of life    
    lastcrl: 20301231235900

digest: sha256
extensions:
    authority_info_access:
        critical: 0
        # ca_issuers and ocsp can be scalar or list
        ca_issuers: http://pki.my.domain/certs/cacerts/[% ISSUER.CN.0 %].crt
        #ocsp: http://ocsp.openxpki.org/

    authority_key_identifier:
        critical: 0
        keyid:  1
        issuer: 1
    issuer_alt_name:        
        critical: 0
        # If the issuer has no subject alternative name, copying returns
        # an empty extension, which is problematic with both RSA SecurId
        # tokens and Cisco devices!
        copy: 0
```

I'm not able to find any errors in the logfiles.
