### ISSUE TITLE
Certificate profiles: Basic Constraint "CA: True" cannot be set

### ISSUE THREAD

**Issue by mbartosch** [openxpki/openxpki#655]
In the profile definition it is possible to set the Basic Constraint CA to true or false. However, regardless of the setting of extensions.basic_constraints.ca the Basic Constraints CA flag in the created end entity certificate is always false.

```
# Profile extensions - set 0/1 as needed
extensions:
    copy: copy

    basic_constraints:
        critical: 1
        ca: 0

```
