### ISSUE TITLE
Basic authentication - EST protocol

### ISSUE THREAD

**Issue by Simkiw** [openxpki/openxpki#893]
Hi,  

I would like to enrol a certificate via EST.  
The client should authenticate itself to the server/openxpki.  
This can be done using
- Certificates
- Challenges password
- Http basic authentication (username, password)

And i'm interested in implementing the last one. However, I haven't seen much covering this section aside from this small paragraph in [openxpki - authentication - advanced usage](https://openxpki.readthedocs.io/en/develop/reference/configuration/realm.html#authentication)

I also noticed the `default.conf` that comes with the openx-config in the tutorial, configured like the following  

```
[auth]
stack = _System
```
So i went in and changed it into `Testing` to use the username/pwd you provide by default.  

But later on, I also realized it might not be enough since there is also an EST configuration associated with the realm.  
And I don't know what to do to make it support the basic auth 

```
authorized_signer:
    rule1:
        # Full DN
        subject: CN=.+:pkiclient,.*
profile:
    cert_profile: tls_server
    cert_subject_style: enroll
```

I'm a bit lost, there is information here and there but I can't make something out of it, and my lack of expertise in linux does not help.  
By the way, I'm using the docker version/repo but I believe it shouldn't be different if i want to authenticate an EST client with basic auth.  

Can anyone guide me through this. Thank you.
