### ISSUE TITLE
Configure options for SSL with MariaDB2 Driver

### ISSUE THREAD

**Issue by jogalt** [openxpki/openxpki#923]
Add options to enable SSL for MariaDB2 database connector in database.yaml

There are no current arguments to support optional/manual ssl.

This can be statically done by adding the below args in the db_connect_params function in MariaDB2.pm

mariadb_ssl_optional => 1
mariadb_ssl => 1

**Comment by oliwel** [comment]
This is already possible, any parameters provided to the `drivers` section are handed to the DBI handler

```yaml
main:
    debug: 0
    type: MariaDB
    ....

    # extra options passed to the driver as parameter
    driver:
        mariadb_ssl_optional: 0
        mariadb_ssl: 1
```
